language: node_js
cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify
node_js:
  - "11"
script:
  - npm test
  - npm run percy-storybook
  - npm run percy-cypress-app:ci
  # after all tests finish running we need
  # to kill all background jobs (like "npm start")
  - kill $(jobs -p) || true
